//! Property-based tests using proptest
//!
//! These tests verify invariants and properties of data structures
//! using random inputs generated by proptest.

use mywheel_rs::array_like::{RepeatArray, ShiftArray};
use mywheel_rs::map_adapter::MapAdapter;
use proptest::prelude::*;

// Property: RepeatArray always returns the same value for any index
proptest! {
    #[test]
    fn prop_repeat_array_constant_value(value in any::<i32>(), size in any::<usize>(), index1 in any::<usize>(), index2 in any::<usize>()) {
        if size == 0 {
            return Ok(());
        }
        let array = RepeatArray::new(value, size);
        let val1 = if index1 < size { array[index1] } else { value };
        let val2 = if index2 < size { array[index2] } else { value };
        assert!(val1 == value && val2 == value && val1 == val2);
    }

    #[test]
    fn prop_repeat_array_length(value in any::<i32>(), size in any::<usize>()) {
        let array = RepeatArray::new(value, size);
        assert_eq!(array.len(), size);
    }

    #[test]
    fn prop_shift_array_indexing(values in any::<Vec<i32>>(), index in any::<usize>()) {
        if values.is_empty() {
            return Ok(());
        }
        let array = ShiftArray::new(values.clone());
        if index < values.len() {
            assert_eq!(array[index], values[index]);
        }
    }

    #[test]
    fn prop_shift_array_length(values in any::<Vec<i32>>()) {
        let array = ShiftArray::new(values.clone());
        assert_eq!(array.len(), values.len());
    }

    #[test]
    fn prop_map_adapter_get_bounds(values in any::<Vec<i32>>(), index in any::<usize>()) {
        let adapter = MapAdapter::new(values);
        assert_eq!(adapter.get(index).is_some(), (index < adapter.len()));
    }

    #[test]
    fn prop_map_adapter_contains_consistency(values in any::<Vec<i32>>(), index in any::<usize>()) {
        let adapter = MapAdapter::new(values);
        assert_eq!(adapter.contains(index), (index < adapter.len()));
    }

    #[test]
    fn prop_map_adapter_values_completeness(values in any::<Vec<i32>>()) {
        let adapter = MapAdapter::new(values.clone());
        assert_eq!(adapter.values().copied().collect::<Vec<_>>(), values);
    }

    #[test]
    fn prop_map_adapter_items_indices(values in any::<Vec<i32>>()) {
        let adapter = MapAdapter::new(values.clone());
        let items: Vec<(usize, i32)> = adapter.items().map(|(i, &v)| (i, v)).collect();
        if items.len() != values.len() {
            panic!("length mismatch");
        }
        assert!(items.iter().enumerate().all(|(i, &(idx, val))| idx == i && val == values[i]));
    }

    #[test]
    fn prop_repeat_array_nonempty(value in any::<i32>(), size in any::<usize>()) {
        let array = RepeatArray::new(value, size);
        if size > 0 {
            assert!(!array.is_empty());
        } else {
            assert!(array.is_empty());
        }
    }
}
