//! Property-based tests using quickcheck
//!
//! These tests verify invariants and properties of data structures
//! using random inputs generated by quickcheck.

use mywheel_rs::array_like::{RepeatArray, ShiftArray};
use mywheel_rs::map_adapter::MapAdapter;
use quickcheck::QuickCheck;

// Property: RepeatArray always returns the same value for any index
#[test]
fn prop_repeat_array_constant_value() {
    fn prop(value: i32, size: usize, index1: usize, index2: usize) -> bool {
        if size == 0 {
            return true;
        }
        let array = RepeatArray::new(value, size);
        let val1 = if index1 < size { array[index1] } else { value };
        let val2 = if index2 < size { array[index2] } else { value };
        val1 == value && val2 == value && val1 == val2
    }
    QuickCheck::new().quickcheck(prop as fn(i32, usize, usize, usize) -> bool);
}

// Property: RepeatArray length is always the size it was created with
#[test]
fn prop_repeat_array_length() {
    fn prop(value: i32, size: usize) -> bool {
        let array = RepeatArray::new(value, size);
        array.len() == size
    }
    QuickCheck::new().quickcheck(prop as fn(i32, usize) -> bool);
}

// Property: ShiftArray maintains consistent indexing
#[test]
fn prop_shift_array_indexing() {
    fn prop(values: Vec<i32>, index: usize) -> bool {
        if values.is_empty() {
            return true;
        }
        let array = ShiftArray::new(values.clone());

        let valid_index = index < values.len();
        if !valid_index {
            return true;
        }

        array[index] == values[index]
    }
    QuickCheck::new().quickcheck(prop as fn(Vec<i32>, usize) -> bool);
}

// Property: ShiftArray length equals number of elements
#[test]
fn prop_shift_array_length() {
    fn prop(values: Vec<i32>) -> bool {
        let array = ShiftArray::new(values.clone());
        array.len() == values.len()
    }
    QuickCheck::new().quickcheck(prop as fn(Vec<i32>) -> bool);
}

// Property: MapAdapter get returns Some only for valid indices
#[test]
fn prop_map_adapter_get_bounds() {
    fn prop(values: Vec<i32>, index: usize) -> bool {
        let adapter = MapAdapter::new(values);
        adapter.get(index).is_some() == (index < adapter.len())
    }
    QuickCheck::new().quickcheck(prop as fn(Vec<i32>, usize) -> bool);
}

// Property: MapAdapter contains returns true only for valid indices
#[test]
fn prop_map_adapter_contains_consistency() {
    fn prop(values: Vec<i32>, index: usize) -> bool {
        let adapter = MapAdapter::new(values);
        adapter.contains(index) == (index < adapter.len())
    }
    QuickCheck::new().quickcheck(prop as fn(Vec<i32>, usize) -> bool);
}

// Property: MapAdapter values iterator returns all elements
#[test]
fn prop_map_adapter_values_completeness() {
    fn prop(values: Vec<i32>) -> bool {
        let adapter = MapAdapter::new(values.clone());
        adapter.values().copied().collect::<Vec<_>>() == values
    }
    QuickCheck::new().quickcheck(prop as fn(Vec<i32>) -> bool);
}

// Property: MapAdapter items iterator returns correct indices
#[test]
fn prop_map_adapter_items_indices() {
    fn prop(values: Vec<i32>) -> bool {
        let adapter = MapAdapter::new(values.clone());
        let items: Vec<(usize, i32)> = adapter.items().map(|(i, &v)| (i, v)).collect();

        if items.len() != values.len() {
            return false;
        }

        items
            .iter()
            .enumerate()
            .all(|(i, &(idx, val))| idx == i && val == values[i])
    }
    QuickCheck::new().quickcheck(prop as fn(Vec<i32>) -> bool);
}

// Property: RepeatArray is never empty if size > 0
#[test]
fn prop_repeat_array_nonempty() {
    fn prop(value: i32, size: usize) -> bool {
        let array = RepeatArray::new(value, size);
        if size > 0 {
            !array.is_empty()
        } else {
            array.is_empty()
        }
    }
    QuickCheck::new().quickcheck(prop as fn(i32, usize) -> bool);
}
